### ISSUE TITLE
big-sync.mspec.js use of testUtils.resetSpies does not reset the spies/stubs

### ISSUE THREAD

**Issue by chrisdopuch** [appnexus/sicksync#16]
The stubbed methods in the rsyncSpies object are never reset. The reason that the tests still pass is because each new call to Rsync inits a completely new object. 

This problem should be fixed so that spies can be properly used on the Rsync object(s).

**Comment by joelgriffith** [comment]
Just fixed this in `master`, rsyncSpies now have a `resetAll` method on their prototype, which resets the relevant spies. 

Since the constructor function just returns an instance of the mocks, the `new` usages in big-sync shouldn't create a new copy of the spies since it references an in-memory instance.

As always, I could be wrong, and this issue should be re-opened!
